name: test-makefile-logs

on:
  workflow_dispatch:

jobs:
  test-makefile-logs:
    runs-on: ubuntu-24.04
    env:
      CLICOLOR_FORCE: "1"
      CMAKE_COLOR_DIAGNOSTICS: "ON"

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

    - uses: astral-sh/setup-uv@v7

    - name: Run cmake
      run: |
        env
        uv tool install cmake
        cmake --version
        python -c "print('\033[33mHello, \nworld!\033[0m')"
        echo "cmake_minimum_required(VERSION 3.21)" > CMakeLists.txt
        echo "project(test-package)" >> CMakeLists.txt
        echo "message(WARNING \"A colored warning message from CMake\")" >> CMakeLists.txt
        cmake .
        make -j VERBOSE=1
